# Generated by Django 5.0.6 on 2024-05-30 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_sharedfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharedfile",
            name="filename",
            field=models.CharField(default="before", max_length=256),
        ),
    ]
